### ISSUE TITLE
0.5.4 stuck on loading and doesn't open

### ISSUE THREAD

**Issue by yehiaabdelm** [BloopAI/bloop#1035]
**Describe the bug**
A clear and concise description of what the bug is. If appropriate add a `frontend` or `backend` label.

The app is stuck on loading when starting.

**Expected behavior**
What did you expect to happen?

The app should open

**To Reproduce**
How can we reproduce the bug? Helpful information could include:
- MBP 13" Intel i5 2020

**Screenshots or output**
If applicable, add screenshots to help illustrate the bug.
<img width="1221" alt="image" src="https://github.com/BloopAI/bloop/assets/63256088/2970dee1-08e2-4e83-86d5-d955b2f251cf">

**Additional context**

**Comment by yehiaabdelm** [comment]
```bash
2023-10-10T14:20:33.502915Z DEBUG bleep: effective configuration config=Configuration { config_file: None, source: StateSource { directory: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/local_cache"), state_file: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/repo_state.json"), version_file: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/version.json"), cookie_key: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/cookie_key.bin"), root_dir: "/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep" }, index_dir: "/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep", index_only: false, disable_background: false, disable_fsevents: false, disable_log_write: false, buffer_size: 100000000, repo_buffer_size: 30000000, max_threads: 4, host: "127.0.0.1", port: 7878, answer_api_url: "https://answer.bloop.ai", analytics_key: Some("2KoxvXavinSbc7QhgBC3P1mD1NI"), analytics_key_fe: Some("2KoxphUWDbzArhv8G8owrCv1BIX"), analytics_data_plane: Some("https://blooplouipej.dataplane.rudderstack.com"), sentry_dsn: Some("https://91d3063e3ed84af58f60e7728711b21e@o4504254520426496.ingest.sentry.io/4504254524293120"), sentry_dsn_fe: Some("https://79266c6b7c1e4fbca430019e2acaf941@o4504254520426496.ingest.sentry.io/4504275760775168"), dylib_dir: Some("/Users/yehiaabdelmohsen/Documents/AUC/Fall 2023/bloop.app/Contents/Frameworks"), qdrant_url: "http://127.0.0.1:6334", model_dir: "/Users/yehiaabdelmohsen/Documents/AUC/Fall 2023/bloop.app/Contents/Resources/model", max_chunk_tokens: 256, collection_name: "documents", embedding_batch_size: 1, cognito_userpool_id: Some("eu-west-1_kTIbk0Veh"), cognito_client_id: Some("6iso6185sujqtfttt1ik63sctc"), cognito_auth_url: Some("https://production-github-oauth.auth.eu-west-1.amazoncognito.com/oauth2/authorize"), cognito_mgmt_url: Some("https://auth.bloop.ai"), github_client_id: None, github_client_secret: None, github_app_id: None, github_app_install_id: None, github_app_private_key: None, bot_secret: None, instance_domain: None, frontend_dist: None, embedding_server_url: None }
2023-10-10T14:20:33.557188Z DEBUG bleep::db: loading db from sqlite:///Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/bleep.db?mode=rwc

```

**Comment by ggordonhall** [comment]
Are those the only log lines in your `logs/` dir?

**Comment by yehiaabdelm** [comment]
There are other logs but from days where the app was working.

**Comment by aawdev** [comment]
This has been driving me nuts on windows 11, It's been over a month now and with each new release I keep hoping I can use it to find it stuck loading. I've completely uninstalled and reinstalled dozens of times with various version to no avail. I've even deleted the bloop dir in app data and program files to make sure everything was removed when reinstalling.

**Comment by ggordonhall** [comment]
Hey @yehiaabdelm can you download the `x86_64-apple-darwin-app` artefact from here: https://github.com/BloopAI/bloop/actions/runs/6472146134? Unzip it and install the dmg in `dmg/`. It is a version of bloop with extra initialisation logging (where bloop fails for you): https://github.com/BloopAI/bloop/pull/1036

Once you've installed it, can you try and run it, and post the resulting logs to this thread? This would really help us narrow this problem down!

**Comment by ggordonhall** [comment]
@yehiaabdelm You should be able to access the [dev dmg here](https://s3.eu-west-1.amazonaws.com/binaries.dev.bloop.ai/bloop_0.5.5_x64.dmg).

**Comment by yehiaabdelm** [comment]
Hey @ggordonhall this version works. Here are the logs anyway.
```bash
2023-10-11T11:16:49.171941Z DEBUG bleep: effective configuration config=Configuration { config_file: None, source: StateSource { directory: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/local_cache"), state_file: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/repo_state.json"), version_file: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/version.json"), cookie_key: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/cookie_key.bin"), root_dir: "/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep" }, index_dir: "/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep", index_only: false, disable_background: false, disable_fsevents: false, disable_log_write: false, buffer_size: 100000000, repo_buffer_size: 30000000, max_threads: 4, host: "127.0.0.1", port: 7878, answer_api_url: "https://answer.bloop.ai", analytics_key: Some("2KoxvXavinSbc7QhgBC3P1mD1NI"), analytics_key_fe: Some("2KoxphUWDbzArhv8G8owrCv1BIX"), analytics_data_plane: Some("https://blooplouipej.dataplane.rudderstack.com"), sentry_dsn: Some("https://91d3063e3ed84af58f60e7728711b21e@o4504254520426496.ingest.sentry.io/4504254524293120"), sentry_dsn_fe: Some("https://79266c6b7c1e4fbca430019e2acaf941@o4504254520426496.ingest.sentry.io/4504275760775168"), dylib_dir: Some("/Applications/bloop.app/Contents/Frameworks"), qdrant_url: "http://127.0.0.1:6334", model_dir: "/Applications/bloop.app/Contents/Resources/model", max_chunk_tokens: 256, collection_name: "documents", embedding_batch_size: 1, cognito_userpool_id: Some("eu-west-1_kTIbk0Veh"), cognito_client_id: Some("6iso6185sujqtfttt1ik63sctc"), cognito_auth_url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("production-github-oauth.auth.eu-west-1.amazoncognito.com")), port: None, path: "/oauth2/authorize", query: None, fragment: None }), cognito_mgmt_url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("auth.bloop.ai")), port: None, path: "/", query: None, fragment: None }), bloop_instance_secret: None, bloop_instance_org: None, bot_secret: None, instance_domain: None, frontend_dist: None, embedding_server_url: None }
2023-10-11T11:16:49.175318Z DEBUG bleep::db: loading db from sqlite:///Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/bleep.db?mode=rwc
2023-10-11T11:16:49.265538Z DEBUG bleep::db: successfully connected to DB
2023-10-11T11:16:50.258333Z DEBUG bleep: saving index version
2023-10-11T11:16:50.267155Z DEBUG bleep: initializing indexes
2023-10-11T11:16:50.588872Z  INFO bleep: configuring analytics ...
2023-10-11T11:16:50.628924Z DEBUG bleep: analytics initialized
2023-10-11T11:16:50.652838Z  INFO bleep::periodic::logrotate: removing old logs
2023-10-11T11:16:50.657065Z  INFO bleep::webserver: starting webserver bind=127.0.0.1:7878
2023-10-11T11:16:51.148330Z DEBUG bleep::webserver::github: github auth started interval=3s
2023-10-11T11:18:01.041680Z DEBUG bleep::webserver::github: acquired credentials
2023-10-11T11:18:01.988304Z DEBUG bleep::periodic::remotes: credentials exist
2023-10-11T11:18:02.756620Z  INFO bleep::analytics: sent analytics event...
2023-10-11T11:18:02.757919Z DEBUG bleep::webserver::github: github auth complete
2023-10-11T11:18:03.389291Z DEBUG bleep::periodic::remotes: repo list updated
2023-10-11T11:18:04.390472Z DEBUG bleep::periodic::remotes: updated user user="yehiaabdelm"
2023-10-11T11:18:16.234965Z DEBUG bleep: effective configuration config=Configuration { config_file: None, source: StateSource { directory: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/local_cache"), state_file: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/repo_state.json"), version_file: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/version.json"), cookie_key: Some("/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/cookie_key.bin"), root_dir: "/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep" }, index_dir: "/Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep", index_only: false, disable_background: false, disable_fsevents: false, disable_log_write: false, buffer_size: 100000000, repo_buffer_size: 30000000, max_threads: 4, host: "127.0.0.1", port: 7878, answer_api_url: "https://answer.bloop.ai", analytics_key: Some("2KoxvXavinSbc7QhgBC3P1mD1NI"), analytics_key_fe: Some("2KoxphUWDbzArhv8G8owrCv1BIX"), analytics_data_plane: Some("https://blooplouipej.dataplane.rudderstack.com"), sentry_dsn: Some("https://91d3063e3ed84af58f60e7728711b21e@o4504254520426496.ingest.sentry.io/4504254524293120"), sentry_dsn_fe: Some("https://79266c6b7c1e4fbca430019e2acaf941@o4504254520426496.ingest.sentry.io/4504275760775168"), dylib_dir: Some("/Applications/bloop.app/Contents/Frameworks"), qdrant_url: "http://127.0.0.1:6334", model_dir: "/Applications/bloop.app/Contents/Resources/model", max_chunk_tokens: 256, collection_name: "documents", embedding_batch_size: 1, cognito_userpool_id: Some("eu-west-1_kTIbk0Veh"), cognito_client_id: Some("6iso6185sujqtfttt1ik63sctc"), cognito_auth_url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("production-github-oauth.auth.eu-west-1.amazoncognito.com")), port: None, path: "/oauth2/authorize", query: None, fragment: None }), cognito_mgmt_url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("auth.bloop.ai")), port: None, path: "/", query: None, fragment: None }), bloop_instance_secret: None, bloop_instance_org: None, bot_secret: None, instance_domain: None, frontend_dist: None, embedding_server_url: None }
2023-10-11T11:18:16.237091Z DEBUG bleep::db: loading db from sqlite:///Users/yehiaabdelmohsen/Library/Application Support/ai.bloop.bloop/bleep/bleep.db?mode=rwc
2023-10-11T11:18:16.239112Z DEBUG bleep::db: successfully connected to DB
2023-10-11T11:18:16.417821Z DEBUG bleep: saving index version
2023-10-11T11:18:16.418509Z DEBUG bleep: initializing indexes
2023-10-11T11:18:16.420890Z  INFO bleep: configuring analytics ...
2023-10-11T11:18:16.422949Z DEBUG bleep: analytics initialized
2023-10-11T11:18:16.431810Z  INFO bleep::periodic::logrotate: removing old logs
2023-10-11T11:18:16.432471Z  INFO bleep::webserver: starting webserver bind=127.0.0.1:7878
2023-10-11T11:18:17.354224Z DEBUG bleep::periodic::remotes: updated user user="yehiaabdelm"
2023-10-11T11:18:17.355496Z DEBUG bleep::periodic::remotes: credentials exist
2023-10-11T11:18:18.699761Z DEBUG bleep::periodic::remotes: repo list updated
2023-10-11T11:18:19.617048Z DEBUG bleep::periodic::remotes: updated user user="yehiaabdelm"

```

**Comment by ggordonhall** [comment]
Interesting. Did you delete your index before running 0.5.5?

@aawdev Can you initialise the v0.5.5 version of the app?

**Comment by aawdev** [comment]
> Interesting. Did you delete your index before running 0.5.5?
> 
> @aawdev Can you initialise the v0.5.5 version of the app?

Sorry for the late reply, I am unable to initialize the v0.5.5

I also tried downloading 0.5.6 just now and it is doing the exact same thing. 

<img width="1054" alt="image" src="https://github.com/BloopAI/bloop/assets/89498219/4d380768-c5d5-4a07-a2f1-346fd46d57db">

**Comment by ggordonhall** [comment]
Can you post the latest entry in the `logs` dir? One from 0.5.6? (It's at `%APPDATA%/bloop/bleep/logs`) 0.5.6 has some better logging which should give more insight into this.

**Comment by longsack** [comment]
same type of issue, was running 0.5.5 and it kept error on indexing when I tried to run it.  I uninstalled the software, installed 0.5.6 and it freezes on load (like the pictures above).

With it still loading here is my error log:
2023-10-13T19:28:46.214542Z DEBUG bleep: effective configuration config=Configuration { config_file: None, source: StateSource { directory: Some("C:\\Users\\Jeremy\\AppData\\Roaming\\bloop\\bleep\\local_cache"), state_file: Some("C:\\Users\\Jeremy\\AppData\\Roaming\\bloop\\bleep\\repo_state.json"), version_file: Some("C:\\Users\\Jeremy\\AppData\\Roaming\\bloop\\bleep\\version.json"), cookie_key: Some("C:\\Users\\Jeremy\\AppData\\Roaming\\bloop\\bleep\\cookie_key.bin"), root_dir: "C:\\Users\\Jeremy\\AppData\\Roaming\\bloop\\bleep" }, index_dir: "C:\\Users\\Jeremy\\AppData\\Roaming\\bloop\\bleep", index_only: false, disable_background: false, disable_fsevents: false, disable_log_write: false, buffer_size: 100000000, repo_buffer_size: 30000000, max_threads: 8, host: "127.0.0.1", port: 7878, answer_api_url: "https://answer.bloop.ai", analytics_key: Some("2KoxvXavinSbc7QhgBC3P1mD1NI"), analytics_key_fe: Some("2KoxphUWDbzArhv8G8owrCv1BIX"), analytics_data_plane: Some("https://blooplouipej.dataplane.rudderstack.com"), sentry_dsn: Some("https://91d3063e3ed84af58f60e7728711b21e@o4504254520426496.ingest.sentry.io/4504254524293120"), sentry_dsn_fe: Some("https://79266c6b7c1e4fbca430019e2acaf941@o4504254520426496.ingest.sentry.io/4504275760775168"), dylib_dir: Some("\\\\?\\C:\\Program Files\\bloop\\dylibs"), qdrant_url: "http://127.0.0.1:6334", model_dir: "\\\\?\\C:\\Program Files\\bloop\\model", max_chunk_tokens: 256, collection_name: "documents", embedding_batch_size: 1, cognito_userpool_id: Some("eu-west-1_kTIbk0Veh"), cognito_client_id: Some("6iso6185sujqtfttt1ik63sctc"), cognito_auth_url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("production-github-oauth.auth.eu-west-1.amazoncognito.com")), port: None, path: "/oauth2/authorize", query: None, fragment: None }), cognito_mgmt_url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("auth.bloop.ai")), port: None, path: "/", query: None, fragment: None }), bloop_instance_secret: None, bloop_instance_org: None, bot_secret: None, instance_domain: None, frontend_dist: None, embedding_server_url: None }
2023-10-13T19:28:46.235463Z DEBUG initialize: bleep::db: connected
2023-10-13T19:28:46.400727Z DEBUG bleep: saving index version
2023-10-13T19:28:46.401717Z DEBUG bleep: initializing indexes

**Comment by jimprince** [comment]
For reference, I was able to get around this by deleting the ai.bloop.bloop/qdrant folder in Application Support on Mac. After deleting, the app launched just fine. Interestingly, my experience was that I was on 0.5.6 which was working fine for a while and then suddenly the app wouldn't get past the loading screen.

**Comment by Guanbin-Huang** [comment]
wow!!! it just works!!!!!  awesome!!!

> For reference, I was able to get around this by deleting the ai.bloop.bloop/qdrant folder in Application Support on Mac. After deleting, the app launched just fine. Interestingly, my experience was that I was on 0.5.6 which was working fine for a while and then suddenly the app wouldn't get past the loading screen. Looks like I lost my conversation history by deleting the folder.

**Comment by jimprince** [comment]
Interestingly, this happened to me again. Instead of deleting the whole qdrant folder, I just deleted the storage folder and that seemed to do this trick this time, in case anyone is interested.

**Comment by ggordonhall** [comment]
We've pinned down a couple of possible sources of this behaviour. One (which we've fixed) was that we'd hang when trying to delete non-existent directories on startup: https://github.com/BloopAI/bloop/pull/1061, another is that Qdrant can crash on startup if it hits a limit on the number of open files (https://qdrant.tech/documentation/guides/common-errors/#too-many-files-open-os-error-24). We're still trying to understand how widespread that is.

@jimprince Which folder did you delete exactly?

**Comment by ggordonhall** [comment]
We've released v0.5.7 which fixes a couple of possible causes of this behaviour: https://github.com/BloopAI/bloop/releases/tag/v0.5.7. Post here if it persists!

**Comment by leiwen83** [comment]
Hi @ggordonhall ,

I try build bloop from source code with main branch. The build is ok, but after installing the dmg, I got the same stuck on loading issue.

I also try directly launch bloop from cmdline, seems qdrant need to be launched by hand?
I install [bloop_0.5.7_aarch64.dmg](https://github.com/BloopAI/bloop/releases/download/v0.5.7/bloop_0.5.7_aarch64.dmg), and there is no such kind of loading issue. So what I am missing for the local build img?

```
2023-10-29 19:47:51.339 bloop[94491:3394083] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
The application panicked (crashed).
Message:  qdrant cannot be started
Location: apps/desktop/src-tauri/src/backend.rs:66

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Thx~

**Comment by joyvuu-dave** [comment]
Happened with 0.5.9 on Mac. Fixed by deleting `~/Library/Application\ Support/ai.bloop.bloop/qdrant` folder.

**Comment by ssunjic-adc** [comment]
Still happening on 0.5.10. Noticed it happens in a larger project context, also might happen after git pulls that re-sync sometimes doesn't do the job.
